{
 "title": "Network",
 "tags": [ "Odyssey" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime average",
   "type": "timeseries",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "odyssey_network_node_uptime_weighted_average{instance=~\"$host\",job=\"odysseygo\"}",
     "legendFormat": "Uptime average"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "timeseries",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "odyssey_network_node_uptime_rewarding_stake{instance=~\"$host\",job=\"odysseygo\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "description": "Number of network peers the node is connected to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "odyssey_network_peers{instance=~\"$host\",job=\"odysseygo\"}",
     "legendFormat": "Peers connected"
    }
   ]
  },
  {
   "title": "Network Timing",
   "type": "timeseries",
   "description": "Shows the amount of time this node will wait for a response to a request before considering the request failed, and the average time it takes to get a response to a request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "odyssey_requests_current_timeout{instance=~\"$host\"}",
     "legendFormat": "Timeout"
    },
    {
     "expr": "odyssey_requests_average_latency{instance=~\"$host\"}",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of outstanding requests related to consensus/bootstrapping. Doesn't include handshake messages.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "odyssey_requests_outstanding{instance=~\"$host\"}",
     "legendFormat": "Outstanding Requests"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_accepted_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_frontier_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(odyssey_network_get_ancestors_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_network_put_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_network_multi_put_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_network_get_version_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(odyssey_network_get_peerlist_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(odyssey_network_pull_query_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_network_push_query_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_network_version_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(odyssey_network_ping_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(odyssey_network_pong_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(odyssey_network_get_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_network_chits_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(odyssey_network_app_request_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_network_app_response_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Sent per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_accepted_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_frontier_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(odyssey_network_get_ancestors_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_network_put_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_network_multi_put_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_network_get_version_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(odyssey_network_get_peerlist_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(odyssey_network_pull_query_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_network_push_query_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_network_version_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(odyssey_network_ping_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(odyssey_network_pong_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(odyssey_network_get_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_network_chits_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(odyssey_network_app_request_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_network_app_response_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Received Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_accepted_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_frontier_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(odyssey_network_get_ancestors_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_network_put_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_network_multi_put_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_network_get_version_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(odyssey_network_get_peerlist_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(odyssey_network_pull_query_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_network_push_query_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_network_version_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(odyssey_network_ping_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(odyssey_network_pong_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(odyssey_network_get_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_network_chits_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(odyssey_network_app_request_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_network_app_response_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Sent Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_accepted_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_frontier_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(odyssey_network_get_ancestors_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_network_put_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_network_multi_put_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_network_get_version_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(odyssey_network_get_peerlist_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(odyssey_network_pull_query_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_network_push_query_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_network_version_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(odyssey_network_ping_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(odyssey_network_pong_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(odyssey_network_get_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_network_chits_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(odyssey_network_app_request_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_network_app_response_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Average Received Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(odyssey_network_accepted_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_accepted_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "increase(odyssey_network_get_accepted_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_accepted_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "increase(odyssey_network_get_accepted_frontier_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_accepted_frontier_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "increase(odyssey_network_get_ancestors_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_ancestors_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "increase(odyssey_network_put_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_put_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_network_multi_put_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_multi_put_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "increase(odyssey_network_get_version_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_version_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "increase(odyssey_network_get_peerlist_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_peerlist_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "increase(odyssey_network_pull_query_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_pull_query_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "increase(odyssey_network_push_query_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_push_query_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "increase(odyssey_network_version_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_version_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "increase(odyssey_network_ping_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_ping_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "increase(odyssey_network_pong_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_pong_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "increase(odyssey_network_get_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_network_chits_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_chits_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "increase(odyssey_network_app_gossip_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_app_gossip_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "increase(odyssey_network_app_request_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_app_request_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "increase(odyssey_network_app_response_received_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_app_response_received{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Average Sent Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(odyssey_network_accepted_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_accepted_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "increase(odyssey_network_get_accepted_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_accepted_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "increase(odyssey_network_get_accepted_frontier_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_accepted_frontier_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "increase(odyssey_network_get_ancestors_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_ancestors_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "increase(odyssey_network_put_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_put_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_network_multi_put_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_multi_put_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "increase(odyssey_network_get_version_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_version_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "increase(odyssey_network_get_peerlist_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_peerlist_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "increase(odyssey_network_pull_query_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_pull_query_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "increase(odyssey_network_push_query_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_push_query_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "increase(odyssey_network_version_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_version_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "increase(odyssey_network_ping_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_ping_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "increase(odyssey_network_pong_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_pong_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "increase(odyssey_network_get_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_get_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_network_chits_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_chits_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "increase(odyssey_network_app_gossip_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_app_gossip_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "increase(odyssey_network_app_request_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_app_request_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "increase(odyssey_network_app_response_sent_bytes{instance=~\"$host\",job=\"odysseygo\"}[1m])/increase(odyssey_network_app_response_sent{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Queries Sent per Accepted Container",
   "type": "timeseries",
   "description": "Considers the A-Chain, O-Chain and D-Chain. A lower value indicates vote pipelining (good.) A higher value indicates failed polls (not good.)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "($A + $B) / ($C + $D + $E)", "type": "math" }
   ]
  },
  {
   "title": "Messages Awaiting Send",
   "type": "timeseries",
   "description": "Number of messages that are queued to be sent to peers",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "odyssey_network_throttler_outbound_awaiting_release{instance=~\"$host\"}",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Benched stake",
   "type": "timeseries",
   "description": "Amount of the stake in DIONE that is benched (ignored) because the nodes are unhealthy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "odyssey_A_benchlist_benched_weight{instance=~\"$host\"}/1000000000",
     "legendFormat": "A chain"
    },
    {
     "expr": "odyssey_O_benchlist_benched_weight{instance=~\"$host\"}/1000000000",
     "legendFormat": "O Chain"
    },
    {
     "expr": "odyssey_D_benchlist_benched_weight{instance=~\"$host\"}/1000000000",
     "legendFormat": "D Chain"
    }
   ]
  },
  { "title": "Inbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Inbound Byte Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "odyssey_network_byte_throttler_inbound_awaiting_acquire{instance=~\"$host\"}",
     "legendFormat": "Messages Awaiting Acquire"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "odyssey_network_byte_throttler_inbound_remaining_validator_bytes{instance=~\"$host\"}",
     "legendFormat": "Bytes Remaining"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire bytes from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_network_byte_throttler_inbound_acquire_latency_sum{instance=~\"$host\"}[2m])/increase(odyssey_network_byte_throttler_inbound_acquire_latency_count{instance=~\"$host\"}[2m])",
     "legendFormat": "Acquire"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_network_buffer_throttler_inbound_acquire_latency_sum{instance=~\"$host\"}[2m])/increase(odyssey_network_buffer_throttler_inbound_acquire_latency_count{instance=~\"$host\"}[2m])",
     "legendFormat": "Acquire"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Awaiting Release (Messages Processing)",
   "type": "timeseries",
   "description": "Number of messages that are currently being handled and haven't yet returned their bytes to the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "odyssey_network_byte_throttler_inbound_awaiting_release{instance=~\"$host\"}",
     "legendFormat": "Messages Awaiting Release"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire from the inbound message buffer throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "odyssey_network_buffer_throttler_inbound_awaiting_acquire{instance=~\"$host\"}",
     "legendFormat": "Messages Awaiting"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining At-Large Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "odyssey_network_byte_throttler_inbound_remaining_at_large_bytes{instance=~\"$host\"}",
     "legendFormat": "Remaining Bytes"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound bandwidth throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "odyssey_network_bandwidth_throttler_inbound_awaiting_acquire{instance=~\"$host\"}",
     "legendFormat": "Messages Awaiting Acquire"
    }
   ]
  },
  { "title": "Outbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Outbound Throttler Remaining At-Large Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "odyssey_network_throttler_outbound_remaining_at_large_bytes{instance=~\"$host\"}",
     "legendFormat": "Bytes Remaining"
    }
   ]
  },
  {
   "title": "Outbound Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "odyssey_network_throttler_outbound_remaining_validator_bytes{instance=~\"$host\"}",
     "legendFormat": "Bytes Remaining"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Messages Failed To Send per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_accepted_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_network_get_accepted_frontier_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(odyssey_network_get_ancestors_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_network_put_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_network_multi_put_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_network_get_version_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(odyssey_network_get_peerlist_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(odyssey_network_pull_query_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_network_push_query_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_network_version_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(odyssey_network_ping_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(odyssey_network_pong_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(odyssey_network_chits_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(odyssey_network_app_request_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_network_app_response_failed{instance=~\"$host\",job=\"odysseygo\"}[1m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "Messages Failed To Parse per Minute",
   "type": "timeseries",
   "description": "Number of messages that could not be parsed because they were of unknown type or invalidly formatted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "increase(odyssey_network_msgs_failed_to_parse{instance=~\"$host\"}[1m])>0",
     "legendFormat": "Failed to Parse"
    }
   ]
  },
  {
   "title": "Inbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of inbound messages dropped (not processed) due to expiration in last minute.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "increase(odyssey_O_handler_expired{instance=~\"$host\"}[1m])+increase(odyssey_D_handler_expired{instance=~\"$host\"}[1m])+increase(odyssey_A_handler_expired{instance=~\"$host\"}[1m])",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Outbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of outbound messages dropped (not sent) due to rate-limiting in the last minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "increase(odyssey_network_throttler_outbound_acquire_failures{instance=~\"$host\"}[1m])",
     "legendFormat": "Messages Dropped"
    }
   ]
  },
  {
   "title": "Inbound Connections Dropped due to Rate-Limiting per Minute",
   "type": "timeseries",
   "description": "Number of inbound connections dropped due to inbound connection rate-limiting",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "increase(odyssey_network_inbound_conn_throttler_rate_limited{instance=~\"$host\"}[1m])",
     "legendFormat": "Rate-Limited"
    }
   ]
  },
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Average Message Compression Time (gzip codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(odyssey_network_codec_gzip_push_query_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_push_query_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Push Query"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_put_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_put_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Put"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_peerlist_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_peerlist_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Peer List"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_app_gossip_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_app_gossip_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_app_request_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_app_request_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Request"
    },
    {
     "expr": "(increase(odyssey_network_codec_app_gzip_response_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_app_response_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Average Message Compression Time (gzip codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(odyssey_network_codec_gzip_push_query_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_push_query_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Push Query"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_put_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_put_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Put"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_peerlist_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_peerlist_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Peer List"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_app_gossip_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_app_gossip_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "(increase(odyssey_network_codec_gzip_app_request_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_app_request_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Request"
    },
    {
     "expr": "(increase(odyssey_network_codec_app_gzip_response_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_gzip_app_response_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Total Message Compression Time per Second (zstd codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_codec_zstd_push_query_compress_time_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Push Query"
    },
    {
     "expr": "rate(odyssey_network_codec_zstd_put_compress_time_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Put"
    },
    {
     "expr": "rate(odyssey_network_codec_zstd_peerlist_compress_time_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Peer List"
    },
    {
     "expr": "rate(odyssey_network_codec_zstd_app_gossip_compress_time_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "rate(odyssey_network_codec_zstd_app_request_compress_time_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "App Request"
    },
    {
     "expr": "rate(odyssey_network_codec_zstd_app_response_compress_time_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Average Message Compression Time (zstd codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(odyssey_network_codec_zstd_push_query_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_zstd_push_query_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Push Query"
    },
    {
     "expr": "(increase(odyssey_network_codec_zstd_put_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_zstd_put_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Put"
    },
    {
     "expr": "(increase(odyssey_network_codec_zstd_peerlist_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_zstd_peerlist_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "Peer List"
    },
    {
     "expr": "(increase(odyssey_network_codec_zstd_app_gossip_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_zstd_app_gossip_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Gossip"
    },
    {
     "expr": "(increase(odyssey_network_codec_zstd_app_request_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_zstd_app_request_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Request"
    },
    {
     "expr": "(increase(odyssey_network_codec_app_zstd_response_compress_time_sum{instance=~\"$host\"}[5m])+1)/(increase(odyssey_network_codec_zstd_app_response_compress_time_count{instance=~\"$host\"}[5m])+1)",
     "legendFormat": "App Response"
    }
   ]
  },
  {
   "title": "Bytes Saved by Compression",
   "type": "timeseries",
   "description": "Rate at which we save bytes (don't send/receive them over the network) by compressing messages/receiving compressed messages.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(odyssey_network_multi_put_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound Multiput"
    },
    {
     "expr": "rate(odyssey_network_multi_put_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound Multiput"
    },
    {
     "expr": "rate(odyssey_network_put_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound Put"
    },
    {
     "expr": "rate(odyssey_network_put_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound Put"
    },
    {
     "expr": "rate(odyssey_network_push_query_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound Push Query"
    },
    {
     "expr": "rate(odyssey_network_push_query_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound Push Query"
    },
    {
     "expr": "rate(odyssey_network_peerlist_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound Peer List"
    },
    {
     "expr": "rate(odyssey_network_peerlist_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound Peer List"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound App Gossip"
    },
    {
     "expr": "rate(odyssey_network_app_gossip_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound App Gossip"
    },
    {
     "expr": "rate(odyssey_network_app_request_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound App Request"
    },
    {
     "expr": "rate(odyssey_network_app_request_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound App Request"
    },
    {
     "expr": "rate(odyssey_network_app_response_compression_saved_received_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Inbound App Response"
    },
    {
     "expr": "rate(odyssey_network_app_response_compression_saved_sent_bytes_sum{instance=~\"$host\"}[5m])",
     "legendFormat": "Outbound App Response"
    }
   ]
  }
 ]
}